# Generated by Django 4.2.7 on 2026-01-08 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbanks', '0001_initial'),
        ('blood_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('assigned_blood_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodbanks.bloodbank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('drop_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('ON_THE_WAY', 'On the Way'), ('DELIVERED', 'Delivered')], default='ASSIGNED', max_length=20)),
                ('blood_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood_requests.bloodrequest')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.driver')),
            ],
        ),
    ]
