# Generated by Django 4.2.7 on 2026-01-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodbanks', '0001_initial'),
        ('blood_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('eta_minutes', models.IntegerField()),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_requests.bloodrequest')),
                ('suggested_blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbanks.bloodbank')),
            ],
        ),
    ]
